### ISSUE TITLE
Publish on Maven

### ISSUE THREAD

**Issue by abhishiv** [adamko-dev/kotlinx-serialization-typescript-generator#33]
Hello, it would be great to have this package on maven.

In my case I'm stuck on Maven since am using cloud functions and they require maven pom.xml unless you want to build and upload a jar. All my dependencies including kotlinx.serialization are maven except this packages.

**Comment by aSemy** [comment]
I'll see what I can do. I did start the process of publishing it to Maven Central, but I got lost in all the varying options.

What happens if you add Jitpack as a repository? The pom.xml should be hosted there. What error are you getting?

**Comment by abhishiv** [comment]
Hey @aSemy 

Sorry my mistake - I had no idea about Jitpack. Just tried it and it works beautifully!

Thank you for a great module! In all JVM env this is the only module I could find which handles polymorphism and abstract classes sensibly!

**Comment by aSemy** [comment]
Because of significant deficiencies with the Gradle signing plugin

* https://github.com/gradle/gradle/issues/19903
* https://github.com/gradle/gradle/issues/13470
* https://github.com/gradle/gradle/issues/18477
* https://github.com/gradle/gradle/issues/20934
* https://github.com/gradle/gradle/issues/19842

and Sonatype is very unfriendly in general, especially to non-JVM, non-Maven projects

* https://issues.sonatype.org/browse/OSSRH-67884
* https://issues.sonatype.org/browse/OSSRH-81412
* https://issues.sonatype.org/browse/OSSRH-81414
* https://issues.sonatype.org/browse/OSSRH-81419
* https://issues.sonatype.org/browse/OSSRH-81434
* https://issues.sonatype.org/browse/OSSRH-81435

So at the moment I'm not able to release to Maven Central.

There are some alternatives, but none are really suitable

* While JitPack works, it's JVM only https://jitpack.io/#adamko-dev/kotlinx-serialization-typescript-generator
* GitHub packages *still* requires a users generate and set an authentication token, which is a pain.
* Gradle source dependencies are cool, but really really janky https://blog.gradle.org/introducing-source-dependencies
   ```kotlin
   // ./settings.gradle.kts
   sourceControl {
       gitRepository("https://github.com/adamko-dev/kotlinx-serialization-typescript-generator.git") {
           producesModule("dev.adamko.kxstsgen:kxs-ts-gen-core")
           producesModule("dev.adamko.kxstsgen:versions-platform")
       }
   }
   ```
* Sonatype Snapshots don't live very long

I might try [setting up my own Maven repo...](https://github.com/elect86/magik)

**Comment by aSemy** [comment]
It looks like Maven Central publishing is working now, even if it's janky (I get lots of errors about missing signatures and files, so I have to repetitively publish until the Sonatype Nexus stops complaining). 

I would be nice to set up a GitHub action to automate publishing - but that's another ticket.
